### ISSUE TITLE
Support for session

### ISSUE THREAD

**Issue by lepisma** [brantou/ob-hy#1]
Hello,

I have been recently needing babel integration for `hy` and found your package. This is great!

I was wondering about the support for session in babel. I believe `ob-hy` can support sessions because `hy` does have an repl. I am not sure how other languages' session mode work but an emacs process running an instance of `hy` for each session can *take in* the code blocks and execute it.

Thoughts?

**Comment by brantou** [comment]
I worked hard for two days to add session support, but not robust! 
@lepisma Any question please let me know!

**Comment by lepisma** [comment]
Thanks for working on this! I really appreciate it.

I will check it out soon and let you know if I run into any problems.
